<?php
if(!defined('_TUBEWEB_')) exit; // 개별 페이지 접근 불가

// 품목별 재화등에 관한 상품요약 정보
$item_info = array(
    "wear"=>array(
        "title"=>"의류",
        "code"=>"001",        
        "article"=>array(
            "material"=>array("제품소재", "섬유의 조성 또는 혼용률을 백분율로 표시, 기능성인 경우 성적서 또는 허가서"),
            "color"=>array("색상", ""),
            "size"=>array("치수", ""),
            "maker"=>array("제조사(수입자/병행수입)",  "수입품의 경우 수입자를 함께 표기 (병행수입의 경우 병행수입 여부로 대체 가능)"),
            "madein"=>array("제조국", ""),
            "wash_caution"=>array("세탁방법 및 취급시 주의사항", ""),
            "manufacturing_ym"=>array("제조연월", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),            
            "imported_product"=>array("수입여부", ""),                        
            "kind"=>array("종류", ""),                                    
            "weight"=>array("상품무게", ""),                                                
            "product_length"=>array("상품 가로_세로_높이", ""),                                                            
        )
    ),
    "shoes"=>array(
        "title"=>"구두/신발",
        "code"=>"002",                
        "article"=>array(
            "material"=>array("제품소재", "운동화인 경우에는 겉감, 안감을 구분하여 표시"),
            "color"=>array("색상", ""),
            "size"=>array("치수(발길이,굽높이 정보등등)", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "imported_product"=>array("수입여부", ""),                    
            "kind"=>array("종류", ""),                                                                
            "foot_size"=>array("발길이", ""),                                                                            
            "height"=>array("굽높이", ""),                                                                                        
            "global_height"=>array("해외사이즈", ""),                                                                                                    
            "kc_safety"=>array("KC안전인증 대상 유무", ""),            
            "weight"=>array("상품무게", ""),                                                
            "product_length"=>array("상품 가로_세로_높이", ""),                                                                        
        )
    ),
    "bag"=>array(
        "title"=>"가방",
        "code"=>"003",                        
        "article"=>array(
            "material"=>array("제품소재", ""),        
            "color"=>array("색상", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),            
            "madein"=>array("제조국", ""),            
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "size"=>array("크기,무게", ""),
            "imported_product"=>array("수입여부", ""),                    
            "kind"=>array("종류", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),            
            "product_length"=>array("상품 가로_세로_높이", ""),        
            "weight"=>array("상품무게", ""),                           
        )
    ),
    "fashion"=>array(
        "title"=>"패션잡화(모자/벨트/액세서리)",
        "code"=>"004",                                
        "article"=>array(
            "material"=>array("제품소재", ""),        
            "color"=>array("색상", ""),            
            "size"=>array("치수", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),            
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "age"=>array("사용연령", ""),            
            "imported_product"=>array("수입여부", ""),                                
            "kind"=>array("종류", ""),            
            "manufacturing_ym"=>array("제조연월", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                        
            "weight"=>array("상품무게", ""),          
            "product_length"=>array("상품 가로_세로_높이", ""),        
        )
    ),
    "bedding"=>array(
        "title"=>"침구류/커튼",
        "code"=>"005",         
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "material"=>array("제품소재", ""),
            "color"=>array("색상", ""),
            "size"=>array("치수", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),            
            "madein"=>array("제조국", ""),
            "wash_caution"=>array("세탁방법 및 취급시 주의사항", ""),
            "caution"=>array("취급시 주의사항", ""),            
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "component" =>array("제품구성", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                        
            "capacity"=>array("용량 또는 중량", ""),            
            "delivery"=>array("배송설치비용", ""),
            "safety_number"=>array("안전인증번호", ""),            
            "imported_product"=>array("수입여부", ""),                                             
            "gift_composition"=>array("사은품 구성"),
            "filling"=>array("충전재"),            
            "product_length"=>array("상품 가로_세로_높이", ""),             
            "weight"=>array("상품무게", ""),                      
        )
    ),
    "furniture"=>array(
        "title"=>"가구(침대/소파/싱크대/DIY제품)",
        "code"=>"006",                 
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "color"=>array("색상", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),                        
            "madein"=>array("제조국", ""),            
            "caution"=>array("취급시 주의사항", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "component" =>array("제품구성", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                        
            "weight"=>array("크기,무게", ""),            
            "delivery"=>array("배송설치비용", ""),            
            "released_date"=>array("동일모델 출시년월", ""),            
            "safety_number"=>array("안전인증번호", ""),            
            "imported_product"=>array("수입여부", ""),                                             
            "purity"=>array("주요 소재/순도/밴드재질(시계의경우)", ""),                         
            "exchange_cost"=>array("교환/반품비용", ""),                                     
            "infant_furniture"=>array("유아동침대/매트리스/식탁의자 해당 여부", ""),                                                 
            "electric_product"=>array("전기용품 안전인증 대상 유무", ""),                                                             
            "electric_number"=>array("전기용품 안전인증번호", ""),                                                                         
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                 
            "product_length"=>array("상품 가로_세로_높이", ""),                    
            "package_unit"=>array("포장단위", ""),
        )
    ),
    "image_appliances"=>array(
        "title"=>"영상가전(TV류)",
        "code"=>"007",                         
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                             
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "weight"=>array("크기,무게", ""),                        
            "released_date"=>array("동일모델 출시년월", ""),            
            "display_level"=>array("화면사양", ""),                        
            "safety_number"=>array("안전인증번호", ""),            
            "imported_product"=>array("수입여부", ""),             
            "kc_safety_check"=>array("KC인증필 항목", ""), 
            "product_length"=>array("상품 가로_세로_높이", ""),                                                
            "refund_payment"=>array("으뜸효율가전 환급여부", ""),
        )
    ),
    "home_appliances"=>array(
        "title"=>"가정용전기제품(냉장고/세탁기/식기세척기/전자레인지)",
        "code"=>"008",           
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                                    
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "weight"=>array("크기,무게", ""),                        
            "released_date"=>array("동일모델 출시년월", ""),       
            "safety_number"=>array("안전인증번호", ""),            
            "imported_product"=>array("수입여부", ""),                                                               
            "electric_safety"=>array("전기용품 안전인증", ""),                                 
            "kc_safety_check"=>array("KC인증필 항목", ""),                                                                                        
            "size"=>array("용량/형태", ""),                                                                    
            "product_length"=>array("상품 가로_세로_높이", ""),                                                                                            
            "color"=>array("색상", ""),
            "refund_payment"=>array("으뜸효율가전 환급여부", ""),            
            "certification_number"=>array("전자파적합성평가인증번호", ""),                        

        )
    ),
    "season_appliances"=>array(
        "title"=>"계절가전(에어컨/온풍기)",
        "code"=>"009",                   
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                                    
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "weight"=>array("크기,무게", ""),                        
            "released_date"=>array("동일모델 출시년월", ""),       
            "safety_number"=>array("안전인증번호", ""),            
            "area"=>array("냉난방면적", ""),
            "installation_costs"=>array("추가설치비용", ""),
            "imported_product"=>array("수입여부", ""),                                                               
            "electric_safety"=>array("전기용품 안전인증", ""),                                 
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),                                                                                            
            "color"=>array("색상", ""),
            "refund_payment"=>array("으뜸효율가전 환급여부", ""),            
            "certification_number"=>array("전자파적합성평가인증번호", ""),                                 
        )
    ),
    "office_appliances"=>array(
        "title"=>"사무용기기(컴퓨터/노트북/프린터)",
        "code"=>"010",
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "specification"=>array("제품 주요 사양", ""),          
            "weight"=>array("크기,무게", ""),                        
            "released_date"=>array("동일모델 출시년월", ""),                     
            "display_level"=>array("화면사양", ""),                
            "safety_number"=>array("안전인증번호", ""),                           
            "certification_check"=>array("전파인증대상 여부", ""),                                       
            "imported_product"=>array("수입여부", ""),             
            "laptop"=>array("노트북 여부", ""),                         
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),                                                                                            
        )
    ),
    "optics_appliances"=>array(
        "title"=>"광학기기(디지털카메라/캠코더)",
        "code"=>"011",        
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "specification"=>array("제품 주요 사양", ""),
            "weight"=>array("크기,무게", ""), 
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),                           
            "certification_check"=>array("전파인증대상 여부", ""), 
            "imported_product"=>array("수입여부", ""),                         
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),                                                       
        )
    ),
    "microelectronics"=>array(
        "title"=>"소형전자(MP3/전자사전등)",
        "code"=>"012",                
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "specification"=>array("제품 주요 사양", ""),
            "weight"=>array("크기,무게", ""), 
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),     
            "certification_check"=>array("전파인증대상 여부", ""), 
            "imported_product"=>array("수입여부", ""),      
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),                                                       
        )
    ),
    "mobile"=>array(
        "title"=>"휴대폰",
        "code"=>"013",           
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "specification"=>array("제품 주요 사양", ""),
            "weight"=>array("크기,무게", ""), 
            "released_date"=>array("동일모델 출시년월", ""),
            "certification_check"=>array("전파인증대상 여부", ""), 
            "join_term"=>array("이동통신 가입조건", ""),
            "imported_product"=>array("수입여부", ""),      
            "telecom"=>array("이동통신사", ""),
            "join_process"=>array("가입절차", ""),            
            "extra_burden"=>array("소비자의 추가적인 부담사항 ", ""),
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),   
            "device_price"=>array("단말가격/지원금/추가지원금", ""),               
        )
    ),
    "navigation"=>array(
        "title"=>"네비게이션",
        "code"=>"014",                   
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "specification"=>array("제품 주요 사양", ""),
            "weight"=>array("크기,무게", ""), 
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),     
            "certification_check"=>array("전파인증대상 여부", ""), 
            "update_cost"=>array("맵 업데이트 비용 및 무상기간", ""),
            "imported_product"=>array("수입여부", ""),      
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "product_length"=>array("상품 가로_세로_높이", ""),   
        )
    ),
    "car"=>array(
        "title"=>"자동차용품(자동차부품/기타자동차용품)",
        "code"=>"015",                           
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),            
            "material"=>array("제품소재", ""),
            "color"=>array("색상", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                        
            "wash_caution"=>array("세탁방법 및 취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),
            "as"=>array("A/S 책임자와 전화번호", ""),
            "components"=>array("제품 구성", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                 
            "capacity"=>array("용량 또는 중량", ""),          
            "weight"=>array("크기,무게", ""), 
            "delivery"=>array("배송설치비용", ""),
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),     
            "apply_model"=>array("적용차종", ""),
            "certification"=>array("자동차부품 자가인증대상 여부", ""),
            "imported_product"=>array("수입여부", ""),                  
            "certification_number"=>array("자동차부품 자가 인증번호", ""),                              
            "caution"=>array("제품사용으로 인한 위험 및 유의사항", ""),                                          
            "product_length"=>array("상품 가로_세로_높이", ""),               
            "test_certification"=>array("검사합격증 번호", ""),                           
        )
    ),
    "medical"=>array(
        "title"=>"의료기기",
        "code"=>"016",                                   
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""), 
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                                    
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),            
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                             
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),     
            "imported_product"=>array("수입여부", ""),      
            "medical_permission"=>array("의료기기 허가 대상여부", ""),                  
            "electric_product"=>array("전기용품 여부", ""),                              
            "appliances_usage"=>array("제품의 사용목적 및 사용방법", ""),
            "advertising_number"=>array("광고사전심의 번호", ""),
            "permission_number"=>array("의료기기 허가 신고번호", ""),            
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "weight"=>array("상품무게", ""),                                  
            "product_length"=>array("상품 가로_세로_높이", ""),                                          
        )
    ),
    "kitchenware"=>array(
        "title"=>"주방용품",
        "code"=>"017",           
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""), 
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                                    
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),            
            "component"=>array("제품 구성", ""),
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                             
            "size"=>array("크기,무게", ""), 
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),                 
            "keep"=>array("보관방법 또는 취급방법", ""),                             
            "material"=>array("재질", ""),
            "imported_product"=>array("수입여부", ""),      
            "expiration_date"=>array("제조연월일(포장일 또는 생산연도) / 유통기한", ""),                  
            "import_declaration"=>array("식품위생법에 따른 수입기구/용기 여부", ""),                              
            "tax_check"=>array("세제여부", ""),                                          
            "usage_standard"=>array("표준 사용량", ""),                                                      
            "usage"=>array("사용 용도", ""),                                                                  
            "unit"=>array("표시단위", ""),                                                                              
            "capacity"=>array("총 용량", ""),                                                                                          
            "unit_capacity"=>array("단위용량", ""),                                                                                                      
            "sale_count"=>array("판매개수", ""),                                                                                                                  
            "product_length"=>array("상품 가로_세로_높이", ""),                                          
            "weight"=>array("상품_무게", ""),            
        )
    ),
    "cosmetics"=>array(
        "title"=>"화장품",
        "code"=>"018",         
        "article"=>array(
            "madein"=>array("제조국", ""),     
            "warranty"=>array("품질보증기준", ""),
            "specification"=>array("제품 주요사양", ""),
            "usage"=>array("사용방법", ""),            
            "mainingredient"=>array("주요성분", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),            
            "imported_product"=>array("수입여부", ""),      
            "expiration_date"=>array("사용기한 또는 개봉 후 사용기간", ""),
            "distributor"=>array("제조자 및 제조판매업자", ""),
            "certification"=>array("식품의약품안전청 심사 내용", ""),
            "caution"=>array("사용할 때 주의사항", ""),            
            "functional_term"=>array("기능성 여부", ""),                        
            "inporter"=>array("수입자", ""),                                    
            "organic_cosmetic"=>array("유기농 화장품에 해당 여부", ""),  
            "organic_ingredient"=>array("유기농 원료 함량", ""), 
            "license_number"=>array("식약청 허가번호", ""), 
            "permission_date"=>array("허가일자", ""),  
            "representative"=>array("대표자명", ""),  
            "classfication"=>array("상품구분", ""),    
            "unit"=>array("표시단위", ""),  
            "capacity"=>array("총 용량", ""), 
            "unit_capacity"=>array("단위 용량", ""), 
            "sale_count"=>array("판매 개수", ""), 
            "weight"=>array("상품무게", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                                         
        )
    ),
    "jewelry"=>array(
        "title"=>"귀금속/보석/시계류",
        "code"=>"019",          
        "article"=>array(
            "size"=>array("치수", ""),
            "maker"=>array("제조사(수입자/병행수입)", ""),          
            "madein"=>array("제조국", ""),                                    
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),
            "specification"=>array("제품 주요 사양", ""),
            "provide_warranty"=>array("품질보증서 제공 유무", ""),
            "capacity"=>array("용량 또는 중량", ""),     
            "imported_product"=>array("수입여부", ""),      
            "purity"=>array("주요 소재/순도/밴드재질(시계의경우)", ""),                  
            "caution"=>array("착용 시 주의사항", ""),
            "grade"=>array("귀금속, 보석류 - 등급", ""),
            "watch_function"=>array("시계 - 기능, 방수 등", ""),            
            "processing_place"=>array("가공지", ""),                        
            "component"=>array("구성품", ""),                              
            "product_length"=>array("상품 가로_세로_높이", ""),                                                     
        )
    ),
    "food"=>array(
        "title"=>"식품(농수산물)",
        "code"=>"020",                  
        "article"=>array(
            "component"=>array("제품 구성", ""), 
            "weight"=>array("용량(중량), 수량, 크기", ""),            
            "law_content"=>array("관련법상 표시사항", ""),
            "keep"=>array("보관방법 또는 취급방법", ""),            
            "as"=>array("소비자상담 관련 전화번호", ""),            
            "raw material"=>array("주원료명", ""),                   
            "location"=>array("생산자 및 소재지", ""),                               
            "imported_product"=>array("수입여부", ""),                                                      
            "manufacturing_ymd"=>array("제조연월일(포장일 또는 생산연도) / 유통기한", ""),
            "ingredients"=>array("함량", ""),                                                                   
            "origin"=>array("원료원산지", ""),                                                                               
            "farm_classify"=>array("농산물 구분 입력", ""),                                                                                           
            "importer"=>array("수입자", ""),                                                                                             
            "law_content"=>array("축산물 구분 입력", ""),                                                                                                                 
            "seafood"=>array("수산물 구분 입력", ""),                                                                                                                             
            "history_mangement"=>array("이력관리표", ""),                                                                                                                                         
            "madein"=>array("제조국", ""),                                    
            "gmo"=>array("GMO여부", ""),                                                  
            "unit"=>array("표시단위", ""),                                                              
            "capacity"=>array("총 용량", ""),                                                              
            "unit_capacity"=>array("단위용량", ""),                                                                                      
            "sale_count"=>array("판매개수", ""),                                                              
            "product_length"=>array("상품 가로_세로_높이", ""),                                               
            "package_unit"=>array("포장단위", ""),                                                                                
            "product_name"=>array("품목 또는 명칭", ""), 
            "caution"=>array("식품등의표시·광고에관한법률에 따른 소비자안전을 위한 주의사항", ""),             
            "report_number"=>array("품목보고번호", ""),
            "safety_check"=>array("안전인증 필 여부 확인", ""),            
        )
    ),
    "general_food"=>array(
        "title"=>"가공식품",
        "code"=>"021",                          
        "article"=>array(
            "weight"=>array("용량(중량), 수량, 크기", ""),            
            "law_content"=>array("관련법상 표시사항", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),            
            "raw material"=>array("주원료명", ""),                   
            "food_type"=>array("식품의 유형", ""),            
            "location"=>array("생산자 및 소재지", ""),    
            "nutrition_component"=>array("영양성분 표시 대상 여부", ""),
            "genetically_modified"=>array("유전자 재조합 식품 여부", ""),
            "special_food"=>array("특수용도식품 여부", ""),            
            "imported_food"=>array("수입식품 여부", ""),
            "display_ad"=>array("표시광고 사전심의필", ""),            
            "manufacturing_ymd"=>array("제조연월일(포장일 또는 생산연도) / 유통기한", ""),            
            "ingredients"=>array("함량", ""),                                                                   
            "origin"=>array("원료원산지", ""),                                                                               
            "importer"=>array("수입자", ""),
            "baby_food"=>array("영유아식 또는 체중조절식품 해당 여부", ""),
            "item"=>array("아이템", ""),                        
            "unit"=>array("표시단위", ""),                                    
            "capacity"=>array("총용량", ""),                                    
            "unit_capacity"=>array("단위용량", ""),                                                
            "sale_count"=>array("판매개수", ""),                                                                        
            "side_effect"=>array("부작용발생 가능성 여부", ""),                      
            "component"=>array("제품 구성", ""), 
            "keep"=>array("보관방법 또는 취급방법", ""),             
            "product_length"=>array("상품 가로_세로_높이", ""),                                               
            "intake"=>array("섭취방법", ""),                                                           
            "package_unit"=>array("포장단위", ""),                                                                       
            "nutrition_component"=>array("영양성분", ""),                   
            "farmed_certification"=>array("유기농산물 인증여부", ""),                               
            "product_name"=>array("제품명", ""),                                           
            "caution"=>array("소비자안전을 위한 주의사항", ""),                                                       
            "report_number"=>array("품목보고번호", ""),                                                                   
            "safety_check"=>array("안전인증 필 여부 확인", ""),                                                                               
        )
    ),
    "diet_food"=>array(
        "title"=>"건강기능식품",
        "code"=>"022",           
        "article"=>array(
            "as"=>array("소비자상담 관련 전화번호", ""),
            "raw material"=>array("주원료명", ""),       
            "food_type"=>array("식품의 유형", ""),
            "location"=>array("생산자 및 소재지", ""),    
            "genetically_modified"=>array("유전자 재조합 식품 여부", ""),
            "imported_food"=>array("수입식품 여부", ""),
            "nutrition"=>array("영양정보", ""),
            "specification"=>array("기능정보", ""),
            "intake"=>array("섭취량, 섭취방법 및 섭취 시 주의사항", ""),
            "disease"=>array("질병예방,치료 의약품 아님 명시", ""),
            "display_ad"=>array("표시광고 사전심의필", ""),
            "manufacturing_ymd"=>array("제조연월일(포장일 또는 생산연도) / 유통기한", ""),            
            "ingredients"=>array("함량", ""),                                                                   
            "origin"=>array("원료원산지", ""),                                                                               
            "pacakge_capacity"=>array("포장단위별 용량(중량), 수량", ""),  
            "importer"=>array("수입자", ""),   
            "unit"=>array("표시단위", ""),                                    
            "capacity"=>array("총용량", ""),                                    
            "unit_capacity"=>array("단위용량", ""),                                                
            "sale_count"=>array("판매개수", ""),                                                                        
            "side_effect"=>array("부작용발생 가능성 여부", ""),   
            "product_length"=>array("상품 가로_세로_높이", ""),                                                                              
            "law_content"=>array("관련법상 표시사항", ""),                                                           
            "product_name"=>array("제품명", ""),                                                                       
            "caution"=>array("소비자안전을 위한 주의사항", ""),                                                                                   
            "safety_check"=>array("안전인증 필 여부 확인", ""),                                                                                               
        )
    ),
    "kids"=>array(
        "title"=>"영유아용품",
        "code"=>"023",                   
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),
            "color"=>array("색상", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),         
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                             
            "released_date"=>array("동일모델 출시년월", ""),
            "safety_number"=>array("안전인증번호", ""),     
            "size"=>array("용량(중량), 수량, 크기", ""),                 
            "material"=>array("재질", ""),                             
            "age"=>array("사용연령", ""),                                         
            "imported_product"=>array("수입여부", ""),      
            "caution"=>array("취급방법 및 주의사항", ""),
            "usage"=>array("사용용도", ""),
            "gift_composition"=>array("사은품 구성", ""),            
            "gift_maker"=>array("사은품 제조사", ""),                        
            "gift_origin"=>array("사은품 원산지", ""),                                    
            "manufacturing_ymd"=>array("제조연월일", ""),            
            "kc_safety_check"=>array("KC인증필 항목", ""),                                     
            "unit"=>array("표시단위", ""),                                    
            "capacity"=>array("총용량", ""),                                    
            "unit_capacity"=>array("단위용량", ""),                                                
            "sale_count"=>array("판매개수", ""),                                                                        
            "package_unit"=>array("포장단위", ""),                                                                                    
            "weight"=>array("상품무게", ""),                                                                                                
            "product_length"=>array("상품 가로_세로_높이", ""),                                        
        )
    ),
    "instrument"=>array(
        "title"=>"악기",
        "code"=>"024",        
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),
            "color"=>array("색상", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),     
            "components"=>array("제품 구성", ""),
            "size"=>array("크기,무게", ""),            
            "released_date"=>array("동일모델 출시년월", ""),
            "material"=>array("재질", ""),
            "imported_product"=>array("수입여부", ""),      
            "detailed_specifications"=>array("상품별 세부 사양", ""),            
            "product_length"=>array("상품 가로_세로_높이", ""),                                                    
        )
    ),
    "sports"=>array(
        "title"=>"스포츠용품",
        "code"=>"025",                
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""),
            "color"=>array("색상", ""),            
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "caution"=>array("취급시 주의사항", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),     
            "components"=>array("제품 구성", ""),
            "released_date"=>array("동일모델 출시년월", ""),
            "size"=>array("용량(중량), 수량, 크기", ""),                 
            "material"=>array("재질", ""),                             
            "imported_product"=>array("수입여부", ""),      
            "kind"=>array("종류", ""),           
            "detailed_specifications"=>array("상품별 세부 사양", ""),                               
            "kc_safety"=>array("KC안전인증 대상 유무", ""),                                         
            "weight"=>array("상품무게", ""),                                                                                                
            "product_length"=>array("상품 가로_세로_높이", ""),                                        
        )
    ),
    "books"=>array(
        "title"=>"서적",
        "code"=>"026",          
        "article"=>array(
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "components"=>array("제품 구성", ""),
            "size"=>array("크기,무게", ""),            
            "product_name"=>array("도서명", ""),
            "author"=>array("저자, 출판사", ""),
            "pages"=>array("쪽수", ""),            
            "publish_date"=>array("출간일", ""),            
            "description"=>array("목차 또는 책소개", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                                        
            "as"=>array("A/S 책임자와 전화번호", ""),     
        )
    ),
    "reserve"=>array(
        "title"=>"호텔/펜션예약",
        "code"=>"027",          
        "article"=>array(
            "location"=>array("국가 또는 지역명", ""),
            "lodgment_type"=>array("숙소형태", ""),
            "grade"=>array("등급, 객실타입", ""),
            "room_capacity"=>array("사용가능인원", ""),
            "facilities"=>array("부대시설, 제공서비스(조식등)", ""),
            "cancellation_policy"=>array("취소규정(환불 위약금 등)", ""),
            "booking_contacts"=>array("예약담당 연락처", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                                        
        )
    ),
    "travel"=>array(
        "title"=>"여행패키지",
        "code"=>"028",        
        "article"=>array(
            "cancellation_policy"=>array("취소규정(환불 위약금 등)", ""),
            "booking_contacts"=>array("예약담당 연락처", ""),            
            "travel_agency"=>array("여행사", ""),
            "flight"=>array("이용항공편", ""),
            "travel_period"=>array("여행기간 및 일정", ""),
            "maximum_people"=>array("총 예정인원, 출발가능 인원", ""),
            "accomodation_info"=>array("숙박정보", ""),
            "details"=>array("포함내역(식사, 인솔자 등)", ""),
            "additional_charge"=>array("추가 경비 항목과 금액", ""),
            "travel_warnings"=>array("해외여행의 경우 외교통상부가 지정하는 여행경보단계", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                                        
        )
    ),
    "airline_ticket"=>array(
        "title"=>"항공권",
        "code"=>"029",                
        "article"=>array(
            "cancellation_policy"=>array("취소규정(환불 위약금 등)", ""),
            "booking_contacts"=>array("예약담당 연락처", ""),            
            "additional_charge"=>array("추가 경비 항목과 금액", ""),
            "charge_condition"=>array("요금조건, 왕복 편도 여부", ""),
            "expiration_date"=>array("유효기간", ""),
            "restriction"=>array("제한사항", ""),
            "ticket_delivery_mean"=>array("티켓수령방법", ""),
            "seat_type"=>array("좌석종류", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                                                    
        )
    ),
    "rent_car"=>array(
        "title"=>"자동차대여서비스(렌터카)",
        "code"=>"030",          
        "article"=>array(
            "model"=>array("적용차종", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),
            "ownership_transfer"=>array("소유권 이전 조건", ""),
            "additional_charge"=>array("추가 비용", ""),
            "fuel_cost"=>array("차량 반환 시 연료대금 정산 방법", ""),
            "vehicle_breakdown"=>array("상품(차량)의 고장/훼손 시 소비자 책임", ""),
            "cancellation_policy"=>array("예약취소 또는 중도 해약 시 환불 기준", ""),
            "ownership_transfer"=>array("소유권 이전 가능 여부", ""),            
            "product_length"=>array("상품 가로_세로_높이", ""),                                                    
        )
    ),
    "rental_water"=>array(
        "title"=>"물품대여서비스(정수기,비데,공기청정기 등)",
        "code"=>"031",              
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""), 
            "rated_voltage"=>array("정격전압,소비전력,에너지소비효율등급", ""),
            "specification"=>array("제품 주요사양", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),            
            "ownership_transfer"=>array("소유권 이전 조건", ""),
            "vehicle_breakdown"=>array("상품(차량)의 고장/훼손 시 소비자 책임", ""),
            "cancellation_policy"=>array("예약취소 또는 중도 해약 시 환불 기준", ""),
            "maintenance"=>array("유지보수 조건", ""),
            "ownership_transfer"=>array("소유권 이전 가능 여부", ""),            
            "product_length"=>array("상품 가로_세로_높이", ""),                                                    
            "rental_fee"=>array("원렌탈료", ""),                                                    
            "installation_costs"=>array("설치비", ""),                                                                
            "register_fee"=>array("등록비", ""),                                                                            
            "extra_burden"=>array("의무사용기간", ""),                                                                                        
            "total_fee"=>array("총 비용", ""),                                                                                                    
        )
    ),
    "rental_etc"=>array(
        "title"=>"물품대여서비스(서적,유아용품,행사용품 등)",
        "code"=>"032",         
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""), 
            "as"=>array("소비자상담 관련 전화번호", ""),            
            "ownership_transfer"=>array("소유권 이전 조건", ""),
            "vehicle_breakdown"=>array("상품(차량)의 고장/훼손 시 소비자 책임", ""),
            "cancellation_policy"=>array("예약취소 또는 중도 해약 시 환불 기준", ""),
            "ownership_transfer"=>array("소유권 이전 가능 여부", ""),            
            "product_length"=>array("상품 가로_세로_높이", ""),                  
        )
    ),
    "digital_contents"=>array(
        "title"=>"디지털콘텐츠(음원,게임,인터넷강의 등)",
        "code"=>"033",           
        "article"=>array(
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "as"=>array("소비자상담 관련 전화번호", ""),    
            "producer"=>array("제작자 또는 공급자", ""),
            "terms_of_use"=>array("이용조건,이용기간 (유효기간)", ""),
            "product_offers"=>array("상품 제공 방식", ""),
            "minimum_system"=>array("최소 시스템 사양, 필수 소프트웨어", ""),
            "maintenance"=>array("청약철회 또는 계약의 해제에 따른 효과", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                  
            "hosting"=>array("주최 또는 기획", ""),                              
            "leading_role"=>array("주연", ""),                                          
            "rating"=>array("관람등급", ""),                                                      
            "concert_time"=>array("상영/공연시간", ""),                                                                  
            "cancellation_policy"=>array("예매 취소 조건", ""),                                                                              
            "cancellation_policy"=>array("취소/환불 방법", ""),                                                                                          
        )
    ),
    "gift_card"=>array(
        "title"=>"상품권/쿠폰",
        "code"=>"034",               
        "article"=>array(
            "as"=>array("소비자상담 관련 전화번호", ""),
            "terms_of_use"=>array("이용조건, 이용기간(유효기간)", ""),
            "isseur"=>array("발행자", ""),
            "use_store"=>array("이용가능매장", ""),
            "refund_policy"=>array("잔액환급조건", ""),
            "product_length"=>array("상품 가로_세로_높이", ""),                  
            "product_name"=>array("품명 및 모델명", ""), 
            "isseur"=>array("발행처", ""),             
            "kind"=>array("종류", ""),                         
            "ticket"=>array("티켓명", ""),                                     
            "coupon_classify"=>array("쿠폰 구분", ""),                                                 
        )
    ),
    "etc"=>array(
        "title"=>"기타",
        "code"=>"035",                       
        "article"=>array(
            "product_name"=>array("품명 및 모델명", ""), 
            "maker"=>array("제조사(수입자/병행수입)", ""),
            "madein"=>array("제조국", ""),
            "warranty"=>array("품질보증기준", ""),            
            "as"=>array("A/S 책임자와 전화번호", ""),     
            "imported_product"=>array("수입여부", ""),      
            "certified_by_law"=>array("법에 의한 인증 허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항", ""),
            "safety_check"=>array("안전인증여부", ""),           
            "unit"=>array("표시단위", ""),         
            "capacity"=>array("총 용량", ""),      
            "unit_capacity"=>array("단위용량", ""),
            "sale_count"=>array("판매개수", ""),  
            "color"=>array("색상", ""),           
            "size"=>array("사이즈", ""),          
            "component"=>array("제품 구성", ""),  
            "material"=>array("재질", ""), 
            "delivery"=>array("배송설치비용", ""), 
            "safety_number"=>array("안전인증번호", ""),
            "weight"=>array("상품_무게", ""), 
            "package_unit"=>array("포장단위", ""), 
            "self_test_number"=>array("자가검사번호", ""),
            "cancellation_policy"=>array("취소/중도해약/해지조건 및 환불방법", ""), 
            "usage_term"=>array("이용조건", ""),
            "counselling_number"=>array("소비자상담 관련 전화번호", ""),            
            "service_provider"=>array("서비스 제공 사업자", ""),                        
            "expiration_date"=>array("제조연월일,유통기한,품질유지기한(기타_유통기간)", ""),                                    
        )
    ),
    "chemicals"=>array(
        "title"=>"생활화학제품",
        "code"=>"036",                       
        "article"=>array(
            "product_name"=>array("품목 및 제품명", ""), 
            "importer"=>array("수입자(수입제품에 한함), 제조국 및 제조사", ""),      
            "caution"=>array("사용상 주의사항", ""),                  
            "safety_standard"=>array("안전기준 적합확인 신고번호(자가검사번호) 또는 안전확인대상 생활화학제품", ""),                              
            "weight"=>array("중량/용량/매수", ""),                                          
            "counselling_number"=>array("소비자상담 관련 전화번호", ""),            
            "expiration_date"=>array("제조연월 및 유통기한", ""),                                    
            "usage"=>array("용도 및 제형", ""),                                                
            "protective_package"=>array("어린이 보호포장 대상 제품 유무", ""),                                                            
            "used_chemical"=>array("제품에 사용된 화학물질 명칭", ""),                                                                        
            "efficacy"=>array("효과/효능", ""),                                                                                    
            "imported_product"=>array("수입여부", ""),                                                                                              
        )
    ),
    "biocidal"=>array(
        "title"=>"살생물제품",
        "code"=>"037",                       
        "article"=>array(
            "product_name"=>array("제품명 및 제품유형", ""), 
            "importer"=>array("수입자(수입제품에 한함), 제조국 및 제조사", ""),      
            "caution"=>array("사용방법 및 사용상 주의사항", ""),                  
            "approval_number"=>array("승인번호", ""),                              
            "weight"=>array("중량 또는 용량 및 표준사용량", ""),                                          
            "counselling_number"=>array("소비자상담 관련 전화번호", ""),            
            "protective_package"=>array("어린이 보호포장 대상 제품 유무", ""),      
            "chemical"=>array("살생물물질, 나노물질, 기타 화학물질(유해화학물질 또는 중점관리물질)의 명칭", ""),      
            "effect"=>array("효과/효능", ""),                  
            "subject_use"=>array("사용대상자 및 사용범위", ""),                  
            "harmfullness"=>array("제품 유해성/위해성 표시", ""),                              
        )
    ),    
    "qa_appliances"=>array(
        "title"=>"[QA심사]가전",
        "code"=>"101",                       
        "article"=>array(
            "import_declaration"=>array("수입신고필증", ""), 
            "imported_food"=>array("식품등의 수입신고확인증", ""),             
            "certification"=>array("KC인증서", ""),                         
            "ktl_test"=>array("KTL시험성적서", ""),                                     
            "suitability"=>array("방송통신기자재등의 적합필증", ""),                                                 
            "license_number"=>array("의료기기품목허가증", ""),                                                             
            "energy_consumption"=>array("에너지소비효율 성적서", ""),                                                                         
        )
    ),   
    "qa_leisure"=>array(
        "title"=>"[QA심사]레포츠",
        "code"=>"102",                       
        "article"=>array(
            "certification"=>array("KC인증서", ""),                                                                                           
        )
    ),            
    "qa_household_goods"=>array(
        "title"=>"[QA심사]생활용품",
        "code"=>"103",                       
        "article"=>array(
            "imported_food"=>array("식품등의 수입신고확인증", ""),                                                                                           
            "test_report"=>array("용출시험성적서(주방)", ""),                                                                                                                   
            "certification"=>array("KC인증서", ""),
        )
    ),                
    "qa_food"=>array(
        "title"=>"[QA심사]식품",
        "code"=>"104",                       
        "article"=>array(
            "imported_food"=>array("식품등의 수입신고확인증", ""),                                                                                           
            "display_ad"=>array("표시광고 증빙서류", ""), 
            "license"=>array("영업허가증", ""),      
            "manufacturing_report"=>array("품목제조보고서", ""),  
            "product_inspection"=>array("완제품검사성적서", ""),
            "package_test"=>array("포장재시험성적서", ""),
            "water_quality"=>array("수질검사성적서", ""),  
            "nutrition_component"=>array("영양성분분석자료", ""),
            "ad_test"=>array("광고심의 필증", ""),
            "origin_certificate"=>array("원산지증명서", ""),            
            "product_sample"=>array("제품샘플", ""),            
            "slaughter_certificate"=>array("도축증명서", ""),            
            "korean_display"=>array("제품 한글표시사항", ""),            
            "grade_test"=>array("등급판정서", ""),                        
        )
    ),                  
    "qa_cosmetic"=>array(
        "title"=>"[QA심사]이미용",
        "code"=>"105",                       
        "article"=>array(
            "import_declaration"=>array("수입신고필증", ""),
            "cosmetic_reg"=>array("화장품 영업 등록필증", ""),
            "certification"=>array("KC인증서", ""),  
            "scheduled_report"=>array("표준통관예정보고서", ""),            
            "ingredient_table"=>array("원료성분표", ""),                        
            "func_certificate"=>array("기능성 인증서", ""),                                    
            "display_ad"=>array("표시광고 증빙서류", ""),                                                
            "medical_permission"=>array("의약외품품목허가서", ""),
            "product_sample"=>array("제품샘플", ""),            
            "whole_ingredient"=>array("전성분표시사진", ""),                        
            "cosmetic_reg"=>array("화장품 제조판매업 등록필증", ""),                        
        )
    ),   
    "qa_kitchenware"=>array(
        "title"=>"[QA심사]주방용품",
        "code"=>"106",                       
        "article"=>array(
            "imported_food"=>array("식품등의 수입신고확인증", ""),                                                                                                       
            "test_report"=>array("용출시험성적서(주방)", ""),                                                                                                                               
            "certification"=>array("KC인증서", ""),  
        )
    ),                            
    "qa_etc"=>array(
        "title"=>"[QA심사]기타",
        "code"=>"107",                       
        "article"=>array(
            "import_declaration"=>array("수입신고필증", ""),            
            "imported_food"=>array("식품등의 수입신고확인증", ""),                                                                                                       
            "test_report"=>array("용출시험성적서(주방)", ""),                                                                                                                               
            "certification"=>array("KC인증서", ""),  
            "radon_report"=>array("라돈성적서", ""),              
            "self_test"=>array("환경부 자가검사성적서", ""),                          
        )
    ),       
    "pre_deliberation"=>array(
        "title"=>"[사전심의관련]",
        "code"=>"108",                       
        "article"=>array(
            "display_ad"=>array("건강기능식품광고 사전 심의필증", ""),            
            "ad_proof"=>array("광고 표현 입증 서류", ""),                        
            "cosmetic_review"=>array("기능성화장품 심사 제외 품목 보고서(제조,수입)", ""),                                    
            "result_report"=>array("기능성화장품(심사,변경심사) 결과통지서", ""),                                                
            "advice_result"=>array("대한화장품협회 광고자문결과", ""),                                                
            "insurance_ad"=>array("보험광고 사전 심의필증", ""),                                                            
            "medical_ad"=>array("의료기기광고 사전 심의필증", ""),
            "clinical_trial_permission"=>array("임상 실험 결과 보고서", ""),            
            "mail_order"=>array("통신판매업 신고증 사본", ""),                        
            "special_food"=>array("특수용도식품광고 사전 심의필증", ""),                                    
            "korean_cosmetic"=>array("한방화장품 한방 성분 함유량 보고서", ""),                                    
            "manufacturing_report"=>array("품목제조보고서", ""),                                    
            "test_review"=>array("시험/검사 성적서", ""),                                                
            "display_ad_document"=>array("표시광고 증빙서류", ""),                                                            
        )
    ),           
);
?>
